/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"
#include "gwin_widget.h"


#define T_Div_Button_ID 0
#define V_Div_Button_ID 1

#define T_Div_List_ID 0
#define V_Div_List_ID 1

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle T_Div_Label;
GHandle V_Div_Label;
GHandle Label_X;
GHandle Label_Y;
GHandle Label_CH1;
GHandle Label_CH2;
GHandle Label_CH;
GHandle X_Acontent_Label;
GHandle X_Bcontent_Label;
GHandle T_Div_Button;
GHandle V_Div_Button;
GHandle Y_Acontent_Label;
GHandle Y_Bcontent_Label;
GHandle X_Fcontent_Label;
GHandle X_ABcontent_Label;
GHandle Y_ABcontent_Label;
GHandle Y_Trgcontent_Label;
GHandle CH1_RMS_content_Label;
GHandle CH1_F_content_Label_;
GHandle CH1_Max_content_Label;
GHandle CH1_PP_content_Label;
GHandle CH1_D_content_Label;
GHandle CH1_Min_content_Label;
GHandle CH1_Pk_content_Label;
GHandle CH1_P_content_Label;
GHandle CH2_content_Label;
GHandle V_Div_List;
GHandle T_Div_List;

// Fonts
font_t dejavu_sans_16;
font_t dejavu_sans_12;
font_t dejavu_sans_10;

static void containerDraw_Back(GWidgetObject* gw, void* param)
{
	(void)param;

	// Clear container area
	gdispGFillArea(gw->g.display, gw->g.x, gw->g.y, gw->g.width, gw->g.height, gw->pstyle->background);

	// Draw the elements
	gdispFillArea(0, 0, 340, 240, black_studio);
}

static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = containerDraw_Back;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);

	// Create label widget: T_Div_Label
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 15;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "10us";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &divc;
	T_Div_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(T_Div_Label, FALSE);
	gwinSetFont(T_Div_Label, dejavu_sans_12);
	gwinRedraw(T_Div_Label);

	// Create label widget: V_Div_Label
	wi.g.show = TRUE;
	wi.g.x = 70;
	wi.g.y = 15;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "0.5V";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &divc;
	V_Div_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(V_Div_Label, FALSE);
	gwinSetFont(V_Div_Label, dejavu_sans_12);
	gwinRedraw(V_Div_Label);

	// Create label widget: Label_X
	wi.g.show = TRUE;
	wi.g.x = 120;
	wi.g.y = 0;
	wi.g.width = 10;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "X";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	Label_X = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_X, FALSE);

	// Create label widget: Label_Y
	wi.g.show = TRUE;
	wi.g.x = 220;
	wi.g.y = 0;
	wi.g.width = 10;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "Y";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Label_Y = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_Y, FALSE);

	// Create label widget: Label_CH1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 200;
	wi.g.width = 40;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "CH1";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	Label_CH1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_CH1, FALSE);

	// Create label widget: Label_CH2
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 220;
	wi.g.width = 40;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "CH2";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Label_CH2 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_CH2, FALSE);

	// Create label widget: Label_CH
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 30;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "CH1";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &divc;
	Label_CH = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_CH, FALSE);
	gwinSetFont(Label_CH, dejavu_sans_12);
	gwinRedraw(Label_CH);

	// Create label widget: X_Acontent_Label
	wi.g.show = TRUE;
	wi.g.x = 130;
	wi.g.y = 0;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_Acontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_Acontent_Label, FALSE);
	gwinSetFont(X_Acontent_Label, dejavu_sans_10);
	gwinRedraw(X_Acontent_Label);

	// Create label widget: X_Bcontent_Label
	wi.g.show = TRUE;
	wi.g.x = 130;
	wi.g.y = 15;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "B:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_Bcontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_Bcontent_Label, FALSE);
	gwinSetFont(X_Bcontent_Label, dejavu_sans_10);
	gwinRedraw(X_Bcontent_Label);

	// create button widget: T_Div_Button
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 0;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "T/Div";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = &divc;
	T_Div_Button = gwinButtonCreate(0, &wi);
	gwinSetTag(V_Div_Button,T_Div_Button_ID);
	gwinSetFont(T_Div_Button, dejavu_sans_12);
	gwinRedraw(T_Div_Button);

	// create button widget: V_Div_Button
	wi.g.show = TRUE;
	wi.g.x = 70;
	wi.g.y = 0;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "V/Div";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = &divc;
	V_Div_Button = gwinButtonCreate(0, &wi);
	gwinSetTag(V_Div_Button,V_Div_Button_ID);
	gwinSetFont(V_Div_Button, dejavu_sans_12);
	gwinRedraw(V_Div_Button);

	// Create label widget: Y_Acontent_Label
	wi.g.show = TRUE;
	wi.g.x = 230;
	wi.g.y = 0;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Y_Acontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_Acontent_Label, FALSE);
	gwinSetFont(Y_Acontent_Label, dejavu_sans_10);
	gwinRedraw(Y_Acontent_Label);

	// Create label widget: Y_Bcontent_Label
	wi.g.show = TRUE;
	wi.g.x = 230;
	wi.g.y = 15;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "B:          ";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Y_Bcontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_Bcontent_Label, FALSE);
	gwinSetFont(Y_Bcontent_Label, dejavu_sans_10);
	gwinRedraw(Y_Bcontent_Label);

	// Create label widget: X_Fcontent_Label
	wi.g.show = TRUE;
	wi.g.x = 170;
	wi.g.y = 0;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "F:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_Fcontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_Fcontent_Label, FALSE);
	gwinSetFont(X_Fcontent_Label, dejavu_sans_10);
	gwinRedraw(X_Fcontent_Label);

	// Create label widget: X_ABcontent_Label
	wi.g.show = TRUE;
	wi.g.x = 170;
	wi.g.y = 15;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A-B:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_ABcontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_ABcontent_Label, FALSE);
	gwinSetFont(X_ABcontent_Label, dejavu_sans_10);
	gwinRedraw(X_ABcontent_Label);

	// Create label widget: Y_ABcontent_Label
	wi.g.show = TRUE;
	wi.g.x = 270;
	wi.g.y = 0;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A-B:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Y_ABcontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_ABcontent_Label, FALSE);
	gwinSetFont(Y_ABcontent_Label, dejavu_sans_10);
	gwinRedraw(Y_ABcontent_Label);

	// Create label widget: Y_Trgcontent_Label
	wi.g.show = TRUE;
	wi.g.x = 270;
	wi.g.y = 15;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "Trg:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &trg;
	Y_Trgcontent_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_Trgcontent_Label, FALSE);
	gwinSetFont(Y_Trgcontent_Label, dejavu_sans_10);
	gwinRedraw(Y_Trgcontent_Label);

	// Create label widget: CH1_RMS_content_Label
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "RMS:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_RMS_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_RMS_content_Label, FALSE);
	gwinSetFont(CH1_RMS_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_RMS_content_Label);

	// Create label widget: CH1_F_content_Label_
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "F:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_F_content_Label_ = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_F_content_Label_, FALSE);
	gwinSetFont(CH1_F_content_Label_, dejavu_sans_10);
	gwinRedraw(CH1_F_content_Label_);

	// Create label widget: CH1_Max_content_Label
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "Max:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_Max_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_Max_content_Label, FALSE);
	gwinSetFont(CH1_Max_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_Max_content_Label);

	// Create label widget: CH1_PP_content_Label
	wi.g.show = TRUE;
	wi.g.x = 180;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "PP:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_PP_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_PP_content_Label, FALSE);
	gwinSetFont(CH1_PP_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_PP_content_Label);

	// Create label widget: CH1_D_content_Label
	wi.g.show = TRUE;
	wi.g.x = 250;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "D:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_D_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_D_content_Label, FALSE);
	gwinSetFont(CH1_D_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_D_content_Label);

	// Create label widget: CH1_Min_content_Label
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "Min:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_Min_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_Min_content_Label, FALSE);
	gwinSetFont(CH1_Min_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_Min_content_Label);

	// Create label widget: CH1_Pk_content_Label
	wi.g.show = TRUE;
	wi.g.x = 180;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "Pk:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_Pk_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_Pk_content_Label, FALSE);
	gwinSetFont(CH1_Pk_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_Pk_content_Label);

	// Create label widget: CH1_P_content_Label
	wi.g.show = TRUE;
	wi.g.x = 250;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "P:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_P_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_P_content_Label, FALSE);
	gwinSetFont(CH1_P_content_Label, dejavu_sans_10);
	gwinRedraw(CH1_P_content_Label);

	// Create label widget: CH2_content_Label
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 220;
	wi.g.width = 280;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	CH2_content_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH2_content_Label, FALSE);
	gwinSetFont(CH2_content_Label, dejavu_sans_10);
	gwinRedraw(CH2_content_Label);

	// Create list widget: V_Div_List
	wi.g.show = FALSE;
	wi.g.x = 70;
	wi.g.y = 30;
	wi.g.width = 50;
	wi.g.height = 70;
	wi.g.parent = ghContainerPage0;
	wi.text = "List1";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &divc;
	V_Div_List = gwinListCreate(0, &wi, FALSE);
	gwinSetTag(V_Div_List,V_Div_List_ID);
	gwinListSetScroll(V_Div_List, scrollSmooth);
	gwinSetFont(V_Div_List, dejavu_sans_12);
	gwinRedraw(V_Div_List);
	gwinListAddItem(V_Div_List, "0.50V", FALSE);
	gwinListAddItem(V_Div_List, "0.25V", FALSE);
	gwinListAddItem(V_Div_List, "0.10V", FALSE);
	gwinListAddItem(V_Div_List, "0.05V", FALSE);

	gwinListSetSelected(V_Div_List, 0, FALSE);
	gwinListSetSelected(V_Div_List, 1, FALSE);
	gwinListSetSelected(V_Div_List, 2, FALSE);
	gwinListSetSelected(V_Div_List, 3, FALSE);
	
	// Create list widget: T_Div_List
	wi.g.show = FALSE;
	wi.g.x = 30;
	wi.g.y = 30;
	wi.g.width = 40;
	wi.g.height = 70;
	wi.g.parent = ghContainerPage0;
	wi.text = "List1";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &divc;
	T_Div_List = gwinListCreate(0, &wi, FALSE);
	gwinSetTag(T_Div_List,T_Div_List_ID);
	gwinListSetScroll(T_Div_List, scrollSmooth);
	gwinSetFont(T_Div_List, dejavu_sans_12);
	gwinRedraw(T_Div_List);
    gwinListAddItem(T_Div_List, "10us", TRUE);
    gwinListAddItem(T_Div_List, "25us", TRUE);
    gwinListAddItem(T_Div_List, "50us", TRUE);
    gwinListAddItem(T_Div_List, "100us", TRUE);
    gwinListAddItem(T_Div_List, "500us", TRUE);
    gwinListAddItem(T_Div_List, "1ms", TRUE);
	gwinListSetSelected(T_Div_List, 0, FALSE);
	gwinListSetSelected(T_Div_List, 1, FALSE);
	gwinListSetSelected(T_Div_List, 2, FALSE);
	gwinListSetSelected(T_Div_List, 3, FALSE);
	gwinListSetSelected(T_Div_List, 4, FALSE);
	gwinListSetSelected(T_Div_List, 5, FALSE);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");
	dejavu_sans_12 = gdispOpenFont("DejaVuSans12");
	dejavu_sans_10 = gdispOpenFont("DejaVuSans10");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);

}
GHandle opened_lst=NULL;
inline void which_btn(uint16_t tag)
{
	switch(tag)
	{
		case T_Div_Button_ID:
			gwinSetVisible(T_Div_List, TRUE);
			opened_lst = T_Div_List;
		break;
		case V_Div_Button_ID:
			gwinSetVisible(V_Div_List, TRUE);
			opened_lst = V_Div_List;
		break;	
	}
}
inline void which_lst(GHandle gh,uint16_t tag,GEvent* pe)
{
	switch(tag)
	{
		case T_Div_List_ID:
			gwinSetText(T_Div_Label,gwinListItemGetText(gh,((GEventGWinList *)pe)->item),TRUE);	
				
		break;
		case V_Div_List_ID:
			gwinSetText(V_Div_Label,gwinListItemGetText(gh,((GEventGWinList *)pe)->item),TRUE);	
				
		break;	
	}
}

void guiEventLoop(void)
{
	GEvent* pe;
	GHandle gh;

	uint16_t tag;
	while (1) 
	{
		// Get an event
		pe = geventEventWait(&glistener, TIME_INFINITE);
		switch (pe->type) 
		{
			case GEVENT_GWIN_BUTTON:
				if(opened_lst!=NULL)
				{
					gwinSetVisible(opened_lst, FALSE);
					opened_lst = NULL;
				}
				gh = ((GEventGWinButton *)pe)->gwin;
				tag= gwinGetTag(gh);
				which_btn(tag);
				//gwinSetText(((GEventGWinButton *)pe)->gwin,"asdf",TRUE);	
			break;
			case GEVENT_GWIN_LIST:
				gh = ((GEventGWinList *)pe)->gwin;
				tag= gwinGetTag(gh);
				if(gwinListItemIsSelected(gh, ((GEventGWinList *)pe)->item))
				{
				//	gwinListSetSelected(V_Div_List, 2, TRUE);
					which_lst(gh,tag,pe);
				//	gwinSetText(V_Div_Label,"asdf",TRUE);	
					gwinSetVisible(gh, FALSE);
				//	gwinRedraw(V_Div_Label);
				}

			
			break;

		}

	}
}

