/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_DEFAULT 0

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle T_Div_Label;
extern GHandle V_Div_Label;
extern GHandle Label_X;
extern GHandle Label_Y;
extern GHandle Label_CH1;
extern GHandle Label_CH2;
extern GHandle Label_CH;
extern GHandle X_Acontent_Label;
extern GHandle X_Bcontent_Label;
extern GHandle T_Div_Button;
extern GHandle D_Div_Button_;
extern GHandle Y_Acontent_Label;
extern GHandle Y_Bcontent_Label;
extern GHandle X_Fcontent_Label;
extern GHandle X_ABcontent_Label;
extern GHandle Y_ABcontent_Label;
extern GHandle Y_Trgcontent_Label;
extern GHandle CH1_RMS_content_Label;
extern GHandle CH1_F_content_Label_;
extern GHandle CH1_Max_content_Label;
extern GHandle CH1_PP_content_Label;
extern GHandle CH1_D_content_Label;
extern GHandle CH1_Min_content_Label;
extern GHandle CH1_Pk_content_Label;
extern GHandle CH1_P_content_Label;
extern GHandle CH2_content_Label;
extern GHandle V_Div_List;
extern GHandle T_Div_List;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

