/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"
#include "gwin_widget.h"

#define DSO_DISP_W	320
#define DSO_DISP_H	170


#define T_Div_Button_ID 0
#define V_Div_Button_ID 1

#define T_Div_List_ID 2
#define V_Div_List_ID 3

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;

GHandle DSO_graph;
//current CHx display on top left
GHandle Label_CH;

GHandle T_Div_Button;
GHandle T_Div_Label;
GHandle T_Div_List;


GHandle V_Div_Button;
GHandle V_Div_Label;
GHandle V_Div_List;

GHandle Label_X;
GHandle X_A_Label;
GHandle X_A_Label_Txt;
GHandle X_B_Label;
GHandle X_B_Label_Txt;
GHandle X_F_Label;
GHandle X_F_Label_Txt;
GHandle X_AB_Label;
GHandle X_AB_Label_Txt;

GHandle Label_Y;
GHandle Y_A_Label;
GHandle Y_A_Label_Txt;
GHandle Y_B_Label;
GHandle Y_B_Label_Txt;
GHandle Y_AB_Label;
GHandle Y_AB_Label_Txt;
GHandle Y_Trg_Label;
GHandle Y_Trg_Label_Txt;

GHandle Label_CH1;
GHandle CH1_RMS_Label;

GHandle CH1_F_Label;
GHandle CH1_F_Label_Txt;
GHandle CH1_Max_Label;
GHandle CH1_Max_Label_Txt;
GHandle CH1_PP_Label;
GHandle CH1_PP_Label_Txt;
GHandle CH1_D_Label;
GHandle CH1_D_Label_Txt;
GHandle CH1_Min_Label;
GHandle CH1_Min_Label_Txt;
GHandle CH1_Pk_Label;
GHandle CH1_Pk_Label_Txt;
GHandle CH1_P_Label;
GHandle CH1_P_Label_Txt;

GHandle Label_CH2;
GHandle CH2_Label;


// Fonts
font_t dejavu_sans_16;
font_t dejavu_sans_12;
font_t dejavu_sans_10;

static void containerDraw_Back(GWidgetObject* gw, void* param)
{
	(void)param;

	// Clear container area
	gdispGFillArea(gw->g.display, gw->g.x, gw->g.y, gw->g.width, gw->g.height, gw->pstyle->background);

	// Draw the elements
	gdispFillArea(0, 0, 340, 240, black_studio);
}
//static GGraphObject GGO;
// A graph styling
/*
static GGraphStyle GraphStyle1 = {
    { GGRAPH_POINT_DOT, 0, Blue },          // Point
    { GGRAPH_LINE_NONE, 2, Gray },          // Line
    { GGRAPH_LINE_SOLID, 0, White },        // X axis
    { GGRAPH_LINE_SOLID, 0, White },        // Y axis
    { GGRAPH_LINE_DASH, 5, Gray, 50 },      // X grid
    { GGRAPH_LINE_DOT, 7, Yellow, 50 },     // Y grid
    GWIN_GRAPH_STYLE_POSITIVE_AXIS_ARROWS   // Flags
};
*/
static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = containerDraw_Back;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);



	// Create the graph window
	/*
	GWindowInit win;
	win.show = TRUE;
	win.x = 0;
	win.y = 30;
	win.width = DSO_DISP_W;
	win.height = DSO_DISP_H;
	win.parent =ghContainerPage0;
	DSO_graph = gwinGraphCreate( &GGO,&win);
   // Set the graph origin and style
    gwinGraphSetOrigin(DSO_graph, DSO_DISP_W/2, DSO_DISP_H/2);
    gwinGraphSetStyle(DSO_graph, &GraphStyle1);
    gwinGraphDrawAxis(DSO_graph);
    gwinRedraw(DSO_graph);
	*/
	/*
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 30;
	wi.g.width = DSO_DISP_W;
	wi.g.height = DSO_DISP_H;
	wi.g.parent =ghContainerPage0;
	DSO_graph = gwinGraphCreate(0,&wi.g);
   // Set the graph origin and style
	
    gwinGraphSetOrigin(DSO_graph, DSO_DISP_W/2, DSO_DISP_H/2);
    gwinGraphSetStyle(DSO_graph, &GraphStyle1);
    gwinGraphDrawAxis(DSO_graph);
    gwinRedraw(DSO_graph);
	*/

	// Create label widget: T_Div_Label
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 15;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "10us";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &divc;
	T_Div_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(T_Div_Label, FALSE);
	gwinSetFont(T_Div_Label, dejavu_sans_12);
	gwinRedraw(T_Div_Label);

	// Create label widget: V_Div_Label
	wi.g.show = TRUE;
	wi.g.x = 70;
	wi.g.y = 15;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "0.5V";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &divc;
	V_Div_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(V_Div_Label, FALSE);
	gwinSetFont(V_Div_Label, dejavu_sans_12);
	gwinRedraw(V_Div_Label);

	// Create label widget: Label_X
	wi.g.show = TRUE;
	wi.g.x = 120;
	wi.g.y = 0;
	wi.g.width = 10;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "X";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	Label_X = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_X, FALSE);

	// Create label widget: Label_Y
	wi.g.show = TRUE;
	wi.g.x = 220;
	wi.g.y = 0;
	wi.g.width = 10;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "Y";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Label_Y = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_Y, FALSE);

	// Create label widget: Label_CH1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 200;
	wi.g.width = 40;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "CH1";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	Label_CH1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_CH1, FALSE);

	// Create label widget: Label_CH2
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 220;
	wi.g.width = 40;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "CH2";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Label_CH2 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_CH2, FALSE);

	// Create label widget: Label_CH
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 30;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "CH1";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &divc;
	Label_CH = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Label_CH, FALSE);
	gwinSetFont(Label_CH, dejavu_sans_12);
	gwinRedraw(Label_CH);

	// Create label widget: X_A_Label
	wi.g.show = TRUE;
	wi.g.x = 130;
	wi.g.y = 0;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_A_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_A_Label, FALSE);
	gwinSetFont(X_A_Label, dejavu_sans_10);
	gwinRedraw(X_A_Label);

	// Create label widget: X_B_Label
	wi.g.show = TRUE;
	wi.g.x = 130;
	wi.g.y = 15;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "B:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_B_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_B_Label, FALSE);
	gwinSetFont(X_B_Label, dejavu_sans_10);
	gwinRedraw(X_B_Label);

	// create button widget: T_Div_Button
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 0;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "T/Div";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = &divc;
	T_Div_Button = gwinButtonCreate(0, &wi);
	gwinSetTag(T_Div_Button,T_Div_Button_ID);
	gwinSetFont(T_Div_Button, dejavu_sans_12);
	gwinRedraw(T_Div_Button);

	// create button widget: V_Div_Button
	wi.g.show = TRUE;
	wi.g.x = 70;
	wi.g.y = 0;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "V/Div";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = &divc;
	V_Div_Button = gwinButtonCreate(0, &wi);
	gwinSetTag(V_Div_Button,V_Div_Button_ID);
	gwinSetFont(V_Div_Button, dejavu_sans_12);
	gwinRedraw(V_Div_Button);

	// Create label widget: Y_A_Label
	wi.g.show = TRUE;
	wi.g.x = 230;
	wi.g.y = 0;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Y_A_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_A_Label, FALSE);
	gwinSetFont(Y_A_Label, dejavu_sans_10);
	gwinRedraw(Y_A_Label);

	// Create label widget: Y_B_Label
	wi.g.show = TRUE;
	wi.g.x = 230;
	wi.g.y = 15;
	wi.g.width = 40;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "B:          ";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Y_B_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_B_Label, FALSE);
	gwinSetFont(Y_B_Label, dejavu_sans_10);
	gwinRedraw(Y_B_Label);

	// Create label widget: X_F_Label
	wi.g.show = TRUE;
	wi.g.x = 170;
	wi.g.y = 0;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "F:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_F_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_F_Label, FALSE);
	gwinSetFont(X_F_Label, dejavu_sans_10);
	gwinRedraw(X_F_Label);

	// Create label widget: X_AB_Label
	wi.g.show = TRUE;
	wi.g.x = 170;
	wi.g.y = 15;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A-B:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	X_AB_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(X_AB_Label, FALSE);
	gwinSetFont(X_AB_Label, dejavu_sans_10);
	gwinRedraw(X_AB_Label);

	// Create label widget: Y_AB_Label
	wi.g.show = TRUE;
	wi.g.x = 270;
	wi.g.y = 0;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "A-B:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	Y_AB_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_AB_Label, FALSE);
	gwinSetFont(Y_AB_Label, dejavu_sans_10);
	gwinRedraw(Y_AB_Label);

	// Create label widget: Y_Trg_Label
	wi.g.show = TRUE;
	wi.g.x = 270;
	wi.g.y = 15;
	wi.g.width = 50;
	wi.g.height = 15;
	wi.g.parent = ghContainerPage0;
	wi.text = "Trg:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &trg;
	Y_Trg_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(Y_Trg_Label, FALSE);
	gwinSetFont(Y_Trg_Label, dejavu_sans_10);
	gwinRedraw(Y_Trg_Label);

	// Create label widget: CH1_RMS_Label
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "RMS:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_RMS_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_RMS_Label, FALSE);
	gwinSetFont(CH1_RMS_Label, dejavu_sans_10);
	gwinRedraw(CH1_RMS_Label);


	// Create label widget: CH1_F_Label
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "F:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_F_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_F_Label, FALSE);
	gwinSetFont(CH1_F_Label, dejavu_sans_10);
	gwinRedraw(CH1_F_Label);

	// Create label widget: CH1_Max_Label
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "Max:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_Max_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_Max_Label, FALSE);
	gwinSetFont(CH1_Max_Label, dejavu_sans_10);
	gwinRedraw(CH1_Max_Label);

	// Create label widget: CH1_PP_Label
	wi.g.show = TRUE;
	wi.g.x = 180;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "PP:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_PP_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_PP_Label, FALSE);
	gwinSetFont(CH1_PP_Label, dejavu_sans_10);
	gwinRedraw(CH1_PP_Label);

	// Create label widget: CH1_D_Label
	wi.g.show = TRUE;
	wi.g.x = 250;
	wi.g.y = 200;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "D:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_D_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_D_Label, FALSE);
	gwinSetFont(CH1_D_Label, dejavu_sans_10);
	gwinRedraw(CH1_D_Label);

	// Create label widget: CH1_Min_Label
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "Min:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_Min_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_Min_Label, FALSE);
	gwinSetFont(CH1_Min_Label, dejavu_sans_10);
	gwinRedraw(CH1_Min_Label);

	// Create label widget: CH1_Pk_Label
	wi.g.show = TRUE;
	wi.g.x = 180;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "Pk:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_Pk_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_Pk_Label, FALSE);
	gwinSetFont(CH1_Pk_Label, dejavu_sans_10);
	gwinRedraw(CH1_Pk_Label);

	// Create label widget: CH1_P_Label
	wi.g.show = TRUE;
	wi.g.x = 250;
	wi.g.y = 210;
	wi.g.width = 70;
	wi.g.height = 10;
	wi.g.parent = ghContainerPage0;
	wi.text = "P:";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &x;
	CH1_P_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH1_P_Label, FALSE);
	gwinSetFont(CH1_P_Label, dejavu_sans_10);
	gwinRedraw(CH1_P_Label);

	// Create label widget: CH2_Label
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 220;
	wi.g.width = 280;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "";
	wi.customDraw = justifyLeft;
	wi.customParam = 0;
	wi.customStyle = &y;
	CH2_Label = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(CH2_Label, FALSE);
	gwinSetFont(CH2_Label, dejavu_sans_10);
	gwinRedraw(CH2_Label);

	// Create list widget: V_Div_List
	wi.g.show = FALSE;
	wi.g.x = 70;
	wi.g.y = 30;
	wi.g.width = 50;
	wi.g.height = 70;
	wi.g.parent = ghContainerPage0;
	wi.text = "List1";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &divc;
	V_Div_List = gwinListCreate(0, &wi, FALSE);
	gwinSetTag(V_Div_List,V_Div_List_ID);
	gwinListSetScroll(V_Div_List, scrollSmooth);
	gwinSetFont(V_Div_List, dejavu_sans_12);
	gwinRedraw(V_Div_List);
	gwinListAddItem(V_Div_List, "0.50V", FALSE);
	gwinListAddItem(V_Div_List, "0.25V", FALSE);
	gwinListAddItem(V_Div_List, "0.10V", FALSE);
	gwinListAddItem(V_Div_List, "0.05V", FALSE);

	gwinListSetSelected(V_Div_List, 0, FALSE);
	gwinListSetSelected(V_Div_List, 1, FALSE);
	gwinListSetSelected(V_Div_List, 2, FALSE);
	gwinListSetSelected(V_Div_List, 3, FALSE);
	
	// Create list widget: T_Div_List
	wi.g.show = FALSE;
	wi.g.x = 30;
	wi.g.y = 30;
	wi.g.width = 40;
	wi.g.height = 70;
	wi.g.parent = ghContainerPage0;
	wi.text = "List1";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &divc;
	T_Div_List = gwinListCreate(0, &wi, FALSE);
	gwinSetTag(T_Div_List,T_Div_List_ID);
	gwinListSetScroll(T_Div_List, scrollSmooth);
	gwinSetFont(T_Div_List, dejavu_sans_12);
	gwinRedraw(T_Div_List);
    gwinListAddItem(T_Div_List, "10us", TRUE);
    gwinListAddItem(T_Div_List, "25us", TRUE);
    gwinListAddItem(T_Div_List, "50us", TRUE);
    gwinListAddItem(T_Div_List, "100us", TRUE);
    gwinListAddItem(T_Div_List, "500us", TRUE);
    gwinListAddItem(T_Div_List, "1ms", TRUE);
	gwinListSetSelected(T_Div_List, 0, FALSE);
	gwinListSetSelected(T_Div_List, 1, FALSE);
	gwinListSetSelected(T_Div_List, 2, FALSE);
	gwinListSetSelected(T_Div_List, 3, FALSE);
	gwinListSetSelected(T_Div_List, 4, FALSE);
	gwinListSetSelected(T_Div_List, 5, FALSE);


    
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");
	dejavu_sans_12 = gdispOpenFont("DejaVuSans12");
	dejavu_sans_10 = gdispOpenFont("DejaVuSans10");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);

}
GHandle *lst_ptr=NULL;
inline void openLst(uint16_t tag)
{

	switch(tag)
	{
		case T_Div_Button_ID:
			gwinSetVisible(T_Div_List, TRUE);
			lst_ptr = &T_Div_List;
		break;
		case V_Div_Button_ID:
			gwinSetVisible(V_Div_List, TRUE);
			lst_ptr = &V_Div_List;
		break;	
	}
}
inline void setLabelTxt(GHandle gh,uint16_t tag,GEvent* pe)
{
	switch(tag)
	{
		case T_Div_List_ID:
			gwinSetText(T_Div_Label,gwinListItemGetText(gh,((GEventGWinList *)pe)->item),TRUE);	
		break;
		case V_Div_List_ID:
			gwinSetText(V_Div_Label,gwinListItemGetText(gh,((GEventGWinList *)pe)->item),TRUE);		
		break;	
	}
}

void guiEventLoop(void)
{
	GEvent* pe;
	GHandle gh;

	uint16_t tag;
	while (1) 
	{
		// Get an event
		pe = geventEventWait(&glistener, TIME_INFINITE);
		switch (pe->type) 
		{
			case GEVENT_GWIN_BUTTON:
				if(lst_ptr)
				{
					gwinSetVisible(lst_ptr, FALSE);
					lst_ptr = NULL;
				}
				tag= gwinGetTag(((GEventGWinButton *)pe)->gwin);
				openLst(tag);
			break;
			case GEVENT_GWIN_LIST:
				gh = ((GEventGWinList *)pe)->gwin;
				tag= gwinGetTag(gh);
				if(gwinListItemIsSelected(gh, ((GEventGWinList *)pe)->item))
				{
					setLabelTxt(gh,tag,pe);
					gwinSetVisible(gh, FALSE);
				}
			break;

		}

	}
}

